/**
 * Tous les textes de l'app, en français et en anglais.
 *
 * Le français reste la référence : c'est la langue d'origine et celle des
 * premiers utilisateurs. `Key` dérive de cet objet, donc une clé ajoutée en
 * français sans sa traduction anglaise fait échouer la compilation — ce qui
 * est exactement le rappel qu'on veut.
 *
 * `{n}` est remplacé à l'exécution par `t(key, { n })`.
 */

const fr = {
  // ── Commun ──────────────────────────────────────────────────────
  "common.cancel": "Annuler",
  "common.close": "Fermer",
  "common.delete": "Supprimer",
  "common.retry": "Réessayer",
  "common.later": "Plus tard",
  "common.send": "Envoyer",
  "common.continue": "Continuer",
  "common.optional": "optionnel",

  // ── Entrée dans l'app ───────────────────────────────────────────
  "login.tagline": "Photographie ton frigo, on s'occupe du reste.",
  "login.step1.title": "Photographie ton frigo",
  "login.step1.text":
    "L'app reconnaît les aliments et estime combien de temps ils tiennent.",
  "login.step2.title": "Reçois des recettes",
  "login.step2.text":
    "Des idées avec ce que tu as déjà, en priorisant ce qui périme bientôt.",
  "login.step3.title": "Ne rachète rien en double",
  "login.step3.text": "La liste de courses retire ce qui est encore dans ton frigo.",
  "login.start": "Commencer gratuitement",
  "login.reassure": "Sans installation, sans carte bancaire.",
  "login.haveAccount": "J'ai déjà un compte",
  "login.whatIsIt": "← C'est quoi SmartChef ?",
  "login.email": "Email",
  "login.password": "Mot de passe",
  "login.signIn": "Se connecter",
  "login.signUp": "Créer un compte",
  "login.toSignUp": "Pas de compte ? Créer un compte",
  "login.toSignIn": "Déjà un compte ? Se connecter",

  // ── Accueil d'un nouvel inscrit ─────────────────────────────────
  "onboarding.trialTitle": "7 jours offerts",
  "onboarding.trialSub": "Tout est ouvert, sans carte bancaire.",
  "onboarding.perk1": "Photographie ton frigo, l'app reconnaît les aliments",
  "onboarding.perk2": "Le plan de la semaine, composé avec ce que tu as",
  "onboarding.perk3": "La liste de courses, sans racheter ce que tu possèdes",
  "onboarding.go": "C'est parti",
  "onboarding.title": "Une seule question",
  "onboarding.sub":
    "Pour ne jamais te proposer quelque chose que tu ne peux pas manger.",
  "onboarding.diet": "Ton régime",
  "onboarding.allergies": "Des allergies ?",
  "onboarding.otherAllergy": "Autre allergie (séparées par une virgule)",
  "onboarding.finish": "Scanner mon frigo",
  "onboarding.editable": "Modifiable à tout moment dans ton profil.",
  "onboarding.expired": "Session expirée, reconnectez-vous.",

  // ── Frigo ───────────────────────────────────────────────────────
  "inventory.title": "Mon frigo",
  "inventory.empty": "Rien pour l'instant",
  "inventory.count": "{n} aliment",
  "inventory.countPlural": "{n} aliments",
  "inventory.emptyTitle": "Commence par une photo",
  "inventory.emptyBody":
    "Prends ton frigo en photo, on identifie les aliments pour toi.",
  "inventory.scan": "Scanner mon frigo",
  "inventory.analysing": "Analyse de la photo…",
  "inventory.detected": "{n} aliment détecté",
  "inventory.detectedPlural": "{n} aliments détectés",
  "inventory.review": "Vérifie et corrige avant d'ajouter.",
  "inventory.name": "Nom",
  "inventory.qty": "Qté",
  "inventory.expiry": "Date de péremption (AAAA-MM-JJ)",
  "inventory.expiryHint":
    "Estimation de conservation — corrige si tu connais la vraie date.",
  "inventory.brand": "Marque (optionnel)",
  "inventory.addRow": "Ajouter un article",
  "inventory.save": "Valider et ajouter à l'inventaire",
  "inventory.doubtful": "à vérifier",
  "inventory.urgent": "{n} aliment à consommer rapidement",
  "inventory.urgentPlural": "{n} aliments à consommer rapidement",
  "inventory.remove": "Retirer {name} de l'inventaire",
  "inventory.errScan": "Échec de l'analyse",
  "inventory.errSave": "Échec de l'enregistrement",
  "inventory.errDelete": "Suppression impossible",
  "inventory.errAlerts": "Échec de l'activation des alertes",
  "inventory.alertsRefused": "Notifications refusées — active-les dans les réglages.",

  // ── Péremption ──────────────────────────────────────────────────
  "expiry.today": "à consommer aujourd'hui",
  "expiry.tomorrow": "demain",
  "expiry.inDays": "dans {n} jours",
  "expiry.yesterday": "périmé d'hier",
  "expiry.sinceDays": "périmé depuis {n} j",

  // ── Recherche ───────────────────────────────────────────────────
  "search.title": "Qu'est-ce que je cuisine ?",
  "search.placeholder": "ex. italien ce soir, moins de 20 min…",
  "search.go": "Chercher",
  "search.run": "Lancer la recherche",
  "search.searching": "Recherche de recettes…",
  "search.emptyTitle": "Dis-moi ton envie",
  "search.emptyBody": "Je propose des recettes avec ce que tu as déjà.",
  "search.noResult": "Aucune recette trouvée",
  "search.rephrase": "Essaie de reformuler ta demande.",
  "search.writing": "Écriture de la recette…",
  "search.ingredients": "Ingrédients",
  "search.ingredientsShort": "ingrédients",
  "search.steps": "Préparation",
  "search.minutes": "min",
  "search.servings": "pers.",
  "search.keep": "Garder cette recette",
  "search.kept": "Gardée",
  "search.savedHead": "Tes recettes gardées",
  "search.forget": "Ne plus garder",
  "search.errSearch": "Échec de la recherche",
  "search.errDetail": "Impossible de charger la recette",
  "search.errKeep": "Impossible de garder cette recette",
  "search.errForget": "Suppression impossible",
  "search.chip1": "Rapide ce soir",
  "search.chip2": "Moins de 20 min",
  "search.chip3": "Végétarien",
  "search.chip4": "Avec mon frigo",

  // ── Semaine ─────────────────────────────────────────────────────
  "plan.title": "Ma semaine",
  "plan.generating": "Génération du plan…",
  "plan.wait": "Une trentaine de secondes.",
  "plan.emptyTitle": "Sept jours, zéro question",
  "plan.emptyBody":
    "Je compose ta semaine à partir de ton frigo, ton budget et ton régime.",
  "plan.generate": "Générer ma semaine",
  "plan.regenerate": "Regénérer la semaine",
  "plan.budget": "Budget de la semaine (optionnel)",
  "plan.budgetLabel": "Budget hebdomadaire en euros",
  "plan.cost": "Coût estimé : {cost} €",
  "plan.costBudget": "Coût estimé : {cost} € / budget {budget} €",
  "plan.breakfast": "Petit-déj",
  "plan.lunch": "Déjeuner",
  "plan.dinner": "Dîner",
  "plan.snack": "Collation",
  "plan.noSteps": "Préparation indisponible.",
  "plan.errGenerate": "Échec de la génération",
  "plan.errSteps": "Impossible de charger la préparation",

  // ── Courses ─────────────────────────────────────────────────────
  "shopping.title": "Mes courses",
  "shopping.building": "Construction de la liste…",
  "shopping.emptyTitle": "Rien à racheter en double",
  "shopping.emptyBody": "Je pars de ton plan de repas et je retire ce que tu as déjà.",
  "shopping.generate": "Générer la liste",
  "shopping.regenerate": "Regénérer la liste",
  "shopping.estimate": "Estimation",
  "shopping.checked": "Cochés",
  "shopping.inFridge": "Déjà dans ton frigo (à vérifier)",
  "shopping.readd": "+ ajouter",
  "shopping.store": "J'ai fait mes courses ({n})",
  "shopping.storing": "Rangement…",
  "shopping.stored": "{n} article ajouté à ton frigo",
  "shopping.storedPlural": "{n} articles ajoutés à ton frigo",
  "shopping.needPlan": "Génère d'abord un plan de repas.",
  "shopping.errGenerate": "Échec de la génération",
  "shopping.errCheck": "La coche n'a pas pu être enregistrée.",
  "shopping.errStore": "Impossible de ranger les courses",
  "shopping.toSort": "À ranger",

  // ── Rayons ──────────────────────────────────────────────────────
  "aisle.produce": "Fruits et légumes",
  "aisle.dairy": "Produits laitiers",
  "aisle.meat": "Viande et poisson",
  "aisle.grocery": "Épicerie",
  "aisle.frozen": "Surgelés",
  "aisle.bakery": "Boulangerie",
  "aisle.other": "Autres",

  // ── J'ai cuisiné ça ─────────────────────────────────────────────
  "cooked.button": "J'ai cuisiné ça",
  "cooked.label": "Marquer cette recette comme cuisinée",
  "cooked.question": "Qu'est-ce que tu as fini ?",
  "cooked.remove": "Retirer de mon frigo",
  "cooked.done": "Frigo mis à jour",
  "cooked.nothing": "Rien à retirer",

  // ── Profil ──────────────────────────────────────────────────────
  "profile.title": "Profil",
  "profile.budget": "Budget hebdo",
  "profile.timePerMeal": "Temps par repas",
  "profile.diet": "Régime",
  "profile.goals": "Objectifs",
  "profile.allergies": "Allergies",
  "profile.noAllergy": "aucune",
  "profile.signOut": "Se déconnecter",
  "profile.signOutLabel": "Se déconnecter de l'application",
  "profile.errSignOut": "Échec de la déconnexion",
  "profile.language": "Langue",

  // ── Premium ─────────────────────────────────────────────────────
  "premium.active": "Premium actif — merci !",
  "premium.upgrade": "Passer en Premium",
  "premium.yourTrial": "Ton essai",
  "premium.perMonth": "/mois",
  "premium.daysLeft": "Accès complet encore {n} jours",
  "premium.lastDay": "Dernier jour d'accès complet",
  "premium.remaining": "Ce qu'il te reste ce mois-ci.",
  "premium.scans": "scans",
  "premium.searches": "recherches",
  "premium.willLose": "Ce que tu perdras à la fin de l'essai",
  "premium.withPremium": "Avec Premium",
  "premium.perk1": "Le plan de la semaine, 8 par mois",
  "premium.perk2": "La liste de courses par rayon",
  "premium.perk3": "100 scans et 300 recherches par mois",
  "premium.subscribe": "S'abonner",
  "premium.keepAccess": "Garder l'accès complet",
  "premium.soon": "Le paiement arrive bientôt.",
  "premium.errCheckout": "Impossible d'ouvrir le paiement",
  "premium.discover": "Découvrir Premium",
  "premium.planLocked":
    "Le plan de la semaine compose tes sept jours à partir de ton frigo, de ton budget et de ton régime. Il fait partie de Premium.",
  "premium.shoppingLocked":
    "La liste se construit à partir de ton plan de repas, rangée par rayon, en retirant ce que tu as déjà. Elle fait partie de Premium, comme le plan.",

  // ── Avis ────────────────────────────────────────────────────────
  "feedback.open": "Donner mon avis",
  "feedback.openAgain": "Donner un nouvel avis",
  "feedback.label": "Donner mon avis sur l'application",
  "feedback.title": "Ton avis",
  "feedback.hint": "Sois franc, c'est plus utile que d'être gentil.",
  "feedback.liked": "Qu'est-ce qui t'a plu ?",
  "feedback.missing": "Qu'est-ce qui t'a manqué ou agacé ?",
  "feedback.rate": "Mettre la note de {n} sur 5",
  "feedback.needRating": "Choisis une note",
  "feedback.thanks": "Merci — c'est noté.",
  "feedback.errSend": "Envoi impossible",

  // ── Erreur générale ─────────────────────────────────────────────
  "error.title": "Quelque chose s'est mal passé",
  "error.session": "Session expirée — reconnecte-toi.",
  "error.unreachable": "Impossible de joindre le serveur. Réessaie dans un instant.",
  "error.server": "Le serveur a répondu {code}.",
} as const;

export type Key = keyof typeof fr;

const en: Record<Key, string> = {
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.delete": "Delete",
  "common.retry": "Try again",
  "common.later": "Later",
  "common.send": "Send",
  "common.continue": "Continue",
  "common.optional": "optional",

  "login.tagline": "Snap your fridge, we'll handle the rest.",
  "login.step1.title": "Snap your fridge",
  "login.step1.text":
    "The app spots your food and estimates how long it will keep.",
  "login.step2.title": "Get recipe ideas",
  "login.step2.text":
    "Made with what you already have, starting with what expires soonest.",
  "login.step3.title": "Stop buying doubles",
  "login.step3.text": "Your shopping list drops whatever is still in the fridge.",
  "login.start": "Start free",
  "login.reassure": "Nothing to install, no card needed.",
  "login.haveAccount": "I already have an account",
  "login.whatIsIt": "← What is SmartChef?",
  "login.email": "Email",
  "login.password": "Password",
  "login.signIn": "Sign in",
  "login.signUp": "Create account",
  "login.toSignUp": "No account yet? Create one",
  "login.toSignIn": "Already registered? Sign in",

  "onboarding.trialTitle": "7 days on us",
  "onboarding.trialSub": "Everything unlocked, no card needed.",
  "onboarding.perk1": "Snap your fridge and the app spots your food",
  "onboarding.perk2": "A full week of meals, built around what you have",
  "onboarding.perk3": "A shopping list that skips what you already own",
  "onboarding.go": "Let's go",
  "onboarding.title": "One question only",
  "onboarding.sub": "So we never suggest something you can't eat.",
  "onboarding.diet": "Your diet",
  "onboarding.allergies": "Any allergies?",
  "onboarding.otherAllergy": "Other allergy (comma separated)",
  "onboarding.finish": "Scan my fridge",
  "onboarding.editable": "You can change this anytime in your profile.",
  "onboarding.expired": "Session expired, please sign in again.",

  "inventory.title": "My fridge",
  "inventory.empty": "Nothing yet",
  "inventory.count": "{n} item",
  "inventory.countPlural": "{n} items",
  "inventory.emptyTitle": "Start with a photo",
  "inventory.emptyBody": "Snap your fridge and we'll identify the food for you.",
  "inventory.scan": "Scan my fridge",
  "inventory.analysing": "Reading the photo…",
  "inventory.detected": "{n} item found",
  "inventory.detectedPlural": "{n} items found",
  "inventory.review": "Check and fix before adding.",
  "inventory.name": "Name",
  "inventory.qty": "Qty",
  "inventory.expiry": "Use-by date (YYYY-MM-DD)",
  "inventory.expiryHint": "Estimated shelf life — correct it if you know the real date.",
  "inventory.brand": "Brand (optional)",
  "inventory.addRow": "Add an item",
  "inventory.save": "Add all to my fridge",
  "inventory.doubtful": "check this",
  "inventory.urgent": "{n} item to eat soon",
  "inventory.urgentPlural": "{n} items to eat soon",
  "inventory.remove": "Remove {name} from the fridge",
  "inventory.errScan": "Could not read the photo",
  "inventory.errSave": "Could not save",
  "inventory.errDelete": "Could not remove it",
  "inventory.errAlerts": "Could not turn alerts on",
  "inventory.alertsRefused": "Notifications blocked — turn them on in your settings.",

  "expiry.today": "eat it today",
  "expiry.tomorrow": "tomorrow",
  "expiry.inDays": "in {n} days",
  "expiry.yesterday": "expired yesterday",
  "expiry.sinceDays": "expired {n} days ago",

  "search.title": "What am I cooking?",
  "search.placeholder": "e.g. italian tonight, under 20 min…",
  "search.go": "Search",
  "search.run": "Run the search",
  "search.searching": "Looking for recipes…",
  "search.emptyTitle": "Tell me what you fancy",
  "search.emptyBody": "I'll suggest recipes using what you already have.",
  "search.noResult": "No recipe found",
  "search.rephrase": "Try wording it differently.",
  "search.writing": "Writing the recipe…",
  "search.ingredients": "Ingredients",
  "search.ingredientsShort": "ingredients",
  "search.steps": "Method",
  "search.minutes": "min",
  "search.servings": "servings",
  "search.keep": "Keep this recipe",
  "search.kept": "Kept",
  "search.savedHead": "Your kept recipes",
  "search.forget": "Stop keeping it",
  "search.errSearch": "Search failed",
  "search.errDetail": "Could not load the recipe",
  "search.errKeep": "Could not keep this recipe",
  "search.errForget": "Could not remove it",
  "search.chip1": "Quick tonight",
  "search.chip2": "Under 20 min",
  "search.chip3": "Vegetarian",
  "search.chip4": "From my fridge",

  "plan.title": "My week",
  "plan.generating": "Building your plan…",
  "plan.wait": "About thirty seconds.",
  "plan.emptyTitle": "Seven days, no questions",
  "plan.emptyBody":
    "I'll build your week from your fridge, your budget and your diet.",
  "plan.generate": "Build my week",
  "plan.regenerate": "Rebuild the week",
  "plan.budget": "Budget for the week (optional)",
  "plan.budgetLabel": "Weekly budget in euros",
  "plan.cost": "Estimated cost: €{cost}",
  "plan.costBudget": "Estimated cost: €{cost} / budget €{budget}",
  "plan.breakfast": "Breakfast",
  "plan.lunch": "Lunch",
  "plan.dinner": "Dinner",
  "plan.snack": "Snack",
  "plan.noSteps": "Method not available.",
  "plan.errGenerate": "Could not build the plan",
  "plan.errSteps": "Could not load the method",

  "shopping.title": "My shopping",
  "shopping.building": "Building your list…",
  "shopping.emptyTitle": "Never buy doubles again",
  "shopping.emptyBody":
    "I start from your meal plan and drop what you already have.",
  "shopping.generate": "Build the list",
  "shopping.regenerate": "Rebuild the list",
  "shopping.estimate": "Estimate",
  "shopping.checked": "Ticked",
  "shopping.inFridge": "Already in your fridge (worth checking)",
  "shopping.readd": "+ add",
  "shopping.store": "I've done the shopping ({n})",
  "shopping.storing": "Putting away…",
  "shopping.stored": "{n} item added to your fridge",
  "shopping.storedPlural": "{n} items added to your fridge",
  "shopping.needPlan": "Build a meal plan first.",
  "shopping.errGenerate": "Could not build the list",
  "shopping.errCheck": "That tick could not be saved.",
  "shopping.errStore": "Could not put the shopping away",
  "shopping.toSort": "To sort",

  "aisle.produce": "Fruit and veg",
  "aisle.dairy": "Dairy",
  "aisle.meat": "Meat and fish",
  "aisle.grocery": "Groceries",
  "aisle.frozen": "Frozen",
  "aisle.bakery": "Bakery",
  "aisle.other": "Other",

  "cooked.button": "I cooked this",
  "cooked.label": "Mark this recipe as cooked",
  "cooked.question": "What did you finish?",
  "cooked.remove": "Remove from my fridge",
  "cooked.done": "Fridge updated",
  "cooked.nothing": "Nothing to remove",

  "profile.title": "Profile",
  "profile.budget": "Weekly budget",
  "profile.timePerMeal": "Time per meal",
  "profile.diet": "Diet",
  "profile.goals": "Goals",
  "profile.allergies": "Allergies",
  "profile.noAllergy": "none",
  "profile.signOut": "Sign out",
  "profile.signOutLabel": "Sign out of the app",
  "profile.errSignOut": "Could not sign out",
  "profile.language": "Language",

  "premium.active": "Premium active — thank you!",
  "premium.upgrade": "Go Premium",
  "premium.yourTrial": "Your trial",
  "premium.perMonth": "/month",
  "premium.daysLeft": "Full access for {n} more days",
  "premium.lastDay": "Last day of full access",
  "premium.remaining": "What's left this month.",
  "premium.scans": "scans",
  "premium.searches": "searches",
  "premium.willLose": "What you'll lose when the trial ends",
  "premium.withPremium": "With Premium",
  "premium.perk1": "The weekly plan, 8 per month",
  "premium.perk2": "The shopping list, sorted by aisle",
  "premium.perk3": "100 scans and 300 searches a month",
  "premium.subscribe": "Subscribe",
  "premium.keepAccess": "Keep full access",
  "premium.soon": "Payment is coming soon.",
  "premium.errCheckout": "Could not open the payment page",
  "premium.discover": "See Premium",
  "premium.planLocked":
    "The weekly plan builds your seven days from your fridge, your budget and your diet. It's part of Premium.",
  "premium.shoppingLocked":
    "The list is built from your meal plan, sorted by aisle, minus what you already have. It's part of Premium, like the plan.",

  "feedback.open": "Leave feedback",
  "feedback.openAgain": "Leave more feedback",
  "feedback.label": "Leave feedback about the app",
  "feedback.title": "Your feedback",
  "feedback.hint": "Be blunt — it helps more than being nice.",
  "feedback.liked": "What did you like?",
  "feedback.missing": "What was missing or annoying?",
  "feedback.rate": "Rate it {n} out of 5",
  "feedback.needRating": "Pick a rating",
  "feedback.thanks": "Thank you — noted.",
  "feedback.errSend": "Could not send",

  "error.title": "Something went wrong",
  "error.session": "Session expired — please sign in again.",
  "error.unreachable": "Can't reach the server. Try again in a moment.",
  "error.server": "The server replied {code}.",
};

export const STRINGS = { fr, en } as const;
