project_id = "smartchef"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]

[db]
port = 54322
major_version = 15

[auth]
enabled = true
site_url = "http://localhost:8081"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true
