import type { Key } from "./index";

/**
 * العربية — arabe standard moderne.
 *
 * Écriture de droite à gauche : voir `isRTL` dans `lib/i18n.ts`, qui bascule
 * la mise en page. Les chiffres restent en chiffres arabes occidentaux
 * (0-9), usage dominant dans les interfaces du Moyen-Orient.
 */
export const ar: Record<Key, string> = {
  "common.cancel": "إلغاء",
  "common.close": "إغلاق",
  "common.delete": "حذف",
  "common.retry": "إعادة المحاولة",
  "common.later": "لاحقًا",
  "common.send": "إرسال",
  "common.continue": "متابعة",
  "common.optional": "اختياري",

  "login.tagline": "صوّر ثلاجتك، ونحن نتولى الباقي.",
  "login.step1.title": "صوّر ثلاجتك",
  "login.step1.text": "يتعرّف التطبيق على الأطعمة ويقدّر المدة التي تبقى صالحة فيها.",
  "login.step2.title": "احصل على وصفات",
  "login.step2.text": "أفكار مما لديك بالفعل، بدءًا بما تقترب صلاحيته من الانتهاء.",
  "login.step3.title": "لا تشترِ شيئًا مكرّرًا",
  "login.step3.text": "قائمة التسوق تحذف ما لا يزال في ثلاجتك.",
  "login.start": "ابدأ مجانًا",
  "login.reassure": "بدون تثبيت، وبدون بطاقة بنكية.",
  "login.haveAccount": "لديّ حساب بالفعل",
  "login.whatIsIt": "← ما هو SmartChef؟",
  "login.email": "البريد الإلكتروني",
  "login.password": "كلمة المرور",
  "login.signIn": "تسجيل الدخول",
  "login.signUp": "إنشاء حساب",
  "login.toSignUp": "ليس لديك حساب؟ أنشئ واحدًا",
  "login.toSignIn": "لديك حساب؟ سجّل الدخول",

  "onboarding.trialTitle": "٧ أيام مجانية",
  "onboarding.trialSub": "كل المزايا مفتوحة، بدون بطاقة بنكية.",
  "onboarding.perk1": "صوّر ثلاجتك ويتعرّف التطبيق على الأطعمة",
  "onboarding.perk2": "خطة الأسبوع، مبنية على ما لديك",
  "onboarding.perk3": "قائمة التسوق، بدون شراء ما تملكه",
  "onboarding.go": "هيا بنا",
  "onboarding.title": "سؤال واحد فقط",
  "onboarding.sub": "حتى لا نقترح عليك أبدًا ما لا تستطيع تناوله.",
  "onboarding.diet": "نظامك الغذائي",
  "onboarding.allergies": "هل لديك حساسية؟",
  "onboarding.otherAllergy": "حساسية أخرى (افصل بينها بفاصلة)",
  "onboarding.finish": "مسح ثلاجتي",
  "onboarding.editable": "يمكنك تغييره في أي وقت من ملفك الشخصي.",
  "onboarding.expired": "انتهت الجلسة، سجّل الدخول من جديد.",

  "inventory.title": "ثلاجتي",
  "inventory.empty": "لا شيء بعد",
  "inventory.count": "{n} صنف",
  "inventory.countPlural": "{n} أصناف",
  "inventory.emptyTitle": "ابدأ بصورة",
  "inventory.emptyBody": "صوّر ثلاجتك وسنتعرّف على الأطعمة نيابةً عنك.",
  "inventory.scan": "مسح ثلاجتي",
  "inventory.analysing": "جارٍ تحليل الصورة…",
  "inventory.detected": "تم العثور على {n} صنف",
  "inventory.detectedPlural": "تم العثور على {n} أصناف",
  "inventory.review": "راجع وصحّح قبل الإضافة.",
  "inventory.name": "الاسم",
  "inventory.qty": "الكمية",
  "inventory.expiry": "تاريخ انتهاء الصلاحية (سنة-شهر-يوم)",
  "inventory.expiryHint": "مدة صلاحية تقديرية — صحّحها إذا كنت تعرف التاريخ الحقيقي.",
  "inventory.brand": "العلامة التجارية (اختياري)",
  "inventory.addRow": "إضافة صنف",
  "inventory.save": "إضافة الكل إلى ثلاجتي",
  "inventory.doubtful": "يحتاج مراجعة",
  "inventory.urgent": "{n} صنف يجب استهلاكه قريبًا",
  "inventory.urgentPlural": "{n} أصناف يجب استهلاكها قريبًا",
  "inventory.remove": "إزالة {name} من الثلاجة",
  "inventory.errScan": "تعذّرت قراءة الصورة",
  "inventory.errSave": "تعذّر الحفظ",
  "inventory.errDelete": "تعذّرت الإزالة",
  "inventory.errAlerts": "تعذّر تفعيل التنبيهات",
  "inventory.alertsRefused": "الإشعارات محظورة — فعّلها من الإعدادات.",

  "allergen.peanut": "الفول السوداني",
  "allergen.nuts": "المكسرات",
  "allergen.lactose": "اللاكتوز",
  "allergen.gluten": "الغلوتين",
  "allergen.egg": "البيض",
  "allergen.fish": "السمك",
  "allergen.shellfish": "القشريات",
  "allergen.soy": "الصويا",
  "allergen.add": "إضافة حساسية {name}",
  "allergen.rm": "إزالة حساسية {name}",

  "diet.omnivore": "كل شيء",
  "diet.vegetarian": "نباتي",
  "diet.vegan": "نباتي صرف",
  "diet.glutenfree": "خالٍ من الغلوتين",

  "unit.piece": "حبة",

  "expiry.today": "تناوله اليوم",
  "expiry.tomorrow": "غدًا",
  "expiry.inDays": "خلال {n} أيام",
  "expiry.yesterday": "انتهت صلاحيته أمس",
  "expiry.sinceDays": "انتهت صلاحيته منذ {n} أيام",

  "search.title": "ماذا أطبخ اليوم؟",
  "search.placeholder": "مثال: إيطالي الليلة، أقل من ٢٠ دقيقة…",
  "search.go": "بحث",
  "search.run": "بدء البحث",
  "search.searching": "جارٍ البحث عن وصفات…",
  "search.emptyTitle": "أخبرني بما تشتهيه",
  "search.emptyBody": "أقترح عليك وصفات مما لديك بالفعل.",
  "search.noResult": "لم يُعثر على أي وصفة",
  "search.rephrase": "جرّب صياغتها بطريقة أخرى.",
  "search.writing": "جارٍ كتابة الوصفة…",
  "search.ingredients": "المكوّنات",
  "search.ingredientsShort": "مكوّنات",
  "search.steps": "طريقة التحضير",
  "search.minutes": "دقيقة",
  "search.servings": "أشخاص",
  "search.keep": "حفظ هذه الوصفة",
  "search.kept": "محفوظة",
  "search.savedHead": "وصفاتك المحفوظة",
  "search.forget": "إلغاء الحفظ",
  "search.errSearch": "فشل البحث",
  "search.errDetail": "تعذّر تحميل الوصفة",
  "search.errKeep": "تعذّر حفظ هذه الوصفة",
  "search.errForget": "تعذّرت الإزالة",
  "search.forgetLabel": "إلغاء حفظ {title}",
  "search.keptLabel": "{title} محفوظة",
  "inventory.removeLabel": "إزالة {name} من الثلاجة",
  "shopping.storeLabelOne": "حفظ عنصر واحد في الثلاجة",
  "shopping.storeLabelMany": "حفظ {n} عناصر في الثلاجة",
  "cooked.keepLabel": "الاحتفاظ بـ {name}",
  "cooked.removeLabel": "إزالة {name}",
  "feedback.rateLabel": "إعطاء {n} من 5",
  "premium.gateLabel": "عرض اشتراك بريميوم",
  "premium.gateCta": "اكتشف بريميوم — {price} €/شهر",
  "search.keepLabel": "حفظ {title}",
  "search.chip1": "سريع الليلة",
  "search.chip2": "أقل من ٢٠ دقيقة",
  "search.chip3": "نباتي",
  "search.chip4": "من ثلاجتي",

  "plan.title": "أسبوعي",
  "plan.generating": "جارٍ إعداد خطتك…",
  "plan.wait": "نحو ثلاثين ثانية.",
  "plan.emptyTitle": "سبعة أيام، بلا أسئلة",
  "plan.emptyBody": "أُعدّ أسبوعك انطلاقًا من ثلاجتك وميزانيتك ونظامك الغذائي.",
  "plan.generate": "إعداد أسبوعي",
  "plan.regenerate": "إعادة إعداد الأسبوع",
  "plan.budget": "ميزانية الأسبوع (اختياري)",
  "plan.budgetLabel": "الميزانية الأسبوعية باليورو",
  "plan.cost": "التكلفة التقديرية: {cost} €",
  "plan.costBudget": "التكلفة التقديرية: {cost} € / الميزانية {budget} €",
  "plan.breakfast": "الفطور",
  "plan.lunch": "الغداء",
  "plan.dinner": "العشاء",
  "plan.snack": "وجبة خفيفة",
  "plan.noSteps": "طريقة التحضير غير متاحة.",
  "plan.errGenerate": "تعذّر إعداد الخطة",
  "plan.errSteps": "تعذّر تحميل طريقة التحضير",

  "shopping.title": "تسوّقي",
  "shopping.building": "جارٍ إعداد قائمتك…",
  "shopping.emptyTitle": "لا مزيد من الشراء المكرّر",
  "shopping.emptyBody": "أنطلق من خطة وجباتك وأحذف ما لديك بالفعل.",
  "shopping.generate": "إعداد القائمة",
  "shopping.regenerate": "إعادة إعداد القائمة",
  "shopping.estimate": "تقدير",
  "shopping.checked": "المحدّدة",
  "shopping.inFridge": "موجود في ثلاجتك (يُفضّل التحقق)",
  "shopping.readd": "+ إضافة",
  "shopping.store": "أنهيت التسوّق ({n})",
  "shopping.storing": "جارٍ الترتيب…",
  "shopping.stored": "تمت إضافة {n} صنف إلى ثلاجتك",
  "shopping.storedPlural": "تمت إضافة {n} أصناف إلى ثلاجتك",
  "shopping.needPlan": "أعدّ خطة وجبات أولًا.",
  "shopping.errGenerate": "تعذّر إعداد القائمة",
  "shopping.errCheck": "تعذّر حفظ التحديد.",
  "shopping.errStore": "تعذّر ترتيب المشتريات",
  "shopping.toSort": "للترتيب",
  "shopping.check": "تحديد {name}",
  "shopping.uncheck": "إلغاء تحديد {name}",

  "aisle.produce": "الخضار والفواكه",
  "aisle.dairy": "منتجات الألبان",
  "aisle.meat": "اللحوم والأسماك",
  "aisle.grocery": "البقالة",
  "aisle.frozen": "المجمّدات",
  "aisle.bakery": "المخبوزات",
  "aisle.other": "أخرى",

  "cooked.button": "طبختُ هذا",
  "cooked.label": "وضع علامة على هذه الوصفة كمطبوخة",
  "cooked.question": "ماذا أنهيت؟",
  "cooked.remove": "إزالة من ثلاجتي",
  "cooked.done": "تم تحديث الثلاجة",
  "cooked.nothing": "لا شيء لإزالته",
  "cooked.readError": "تعذرت قراءة محتويات ثلاجتك",

  "profile.title": "الملف الشخصي",
  "profile.budget": "الميزانية الأسبوعية",
  "profile.timePerMeal": "الوقت لكل وجبة",
  "profile.diet": "النظام الغذائي",
  "profile.goals": "الأهداف",
  "profile.allergies": "الحساسية",
  "profile.noAllergy": "لا شيء",
  "profile.signOut": "تسجيل الخروج",
  "profile.signOutLabel": "تسجيل الخروج من التطبيق",
  "profile.errSignOut": "تعذّر تسجيل الخروج",
  "profile.language": "اللغة",

  "premium.active": "Premium مفعّل — شكرًا لك!",
  "premium.upgrade": "الترقية إلى Premium",
  "premium.yourTrial": "فترتك التجريبية",
  "premium.perMonth": "/شهريًا",
  "premium.daysLeft": "وصول كامل لمدة {n} أيام أخرى",
  "premium.lastDay": "آخر يوم من الوصول الكامل",
  "premium.remaining": "ما تبقّى لك هذا الشهر.",
  "premium.scans": "عمليات مسح",
  "premium.searches": "عمليات بحث",
  "premium.willLose": "ما ستفقده عند انتهاء الفترة التجريبية",
  "premium.withPremium": "مع Premium",
  "premium.perk1": "خطة الأسبوع، ٨ مرات شهريًا",
  "premium.perk2": "قائمة التسوق، مرتّبة حسب الأقسام",
  "premium.perk3": "١٠٠ عملية مسح و٣٠٠ بحث شهريًا",
  "premium.subscribe": "اشترك",
  "premium.keepAccess": "الاحتفاظ بالوصول الكامل",
  "premium.soon": "الدفع قادم قريبًا.",
  "premium.errCheckout": "تعذّر فتح صفحة الدفع",
  "premium.discover": "اكتشف Premium",
  "premium.planLocked":
    "خطة الأسبوع تُعدّ أيامك السبعة انطلاقًا من ثلاجتك وميزانيتك ونظامك الغذائي. وهي جزء من Premium.",
  "premium.shoppingLocked":
    "القائمة تُبنى من خطة وجباتك، مرتّبة حسب الأقسام وبدون ما تملكه بالفعل. وهي جزء من Premium، مثل الخطة.",

  "feedback.open": "أرسل رأيك",
  "feedback.openAgain": "أرسل رأيًا آخر",
  "feedback.label": "أرسل رأيك حول التطبيق",
  "feedback.title": "رأيك",
  "feedback.hint": "كن صريحًا، فذلك أنفع من المجاملة.",
  "feedback.liked": "ما الذي أعجبك؟",
  "feedback.missing": "ما الذي نقص أو أزعجك؟",
  "feedback.rate": "منح {n} من ٥",
  "feedback.needRating": "اختر تقييمًا",
  "feedback.thanks": "شكرًا — تم التسجيل.",
  "feedback.errSend": "تعذّر الإرسال",

  "error.title": "حدث خطأ ما",
  "error.session": "انتهت الجلسة — سجّل الدخول من جديد.",
  "error.unreachable": "تعذّر الاتصال بالخادم. حاول بعد قليل.",
  "error.timeout": "يستغرق الخادم وقتًا طويلًا. حاول مرة أخرى بعد قليل.",
  "error.camera": "تم رفض الوصول إلى الكاميرا. اسمح به من الإعدادات.",
  "error.server": "ردّ الخادم بالرمز {code}.",
};
