import type { Key } from "./index";

/** Deutsch. */
export const de: Record<Key, string> = {
  "common.cancel": "Abbrechen",
  "common.close": "Schließen",
  "common.delete": "Löschen",
  "common.retry": "Erneut versuchen",
  "common.later": "Später",
  "common.send": "Senden",
  "common.continue": "Weiter",
  "common.optional": "optional",

  "login.tagline": "Fotografier deinen Kühlschrank, den Rest übernehmen wir.",
  "login.step1.title": "Kühlschrank fotografieren",
  "login.step1.text":
    "Die App erkennt deine Lebensmittel und schätzt, wie lange sie halten.",
  "login.step2.title": "Rezepte bekommen",
  "login.step2.text":
    "Ideen mit dem, was du schon hast — zuerst das, was bald abläuft.",
  "login.step3.title": "Nichts doppelt kaufen",
  "login.step3.text":
    "Die Einkaufsliste streicht, was noch im Kühlschrank liegt.",
  "login.start": "Kostenlos starten",
  "login.reassure": "Keine Installation, keine Kreditkarte.",
  "login.haveAccount": "Ich habe schon ein Konto",
  "login.whatIsIt": "← Was ist SmartChef?",
  "login.email": "E-Mail",
  "login.password": "Passwort",
  "login.signIn": "Anmelden",
  "login.signUp": "Konto erstellen",
  "login.toSignUp": "Noch kein Konto? Jetzt erstellen",
  "login.toSignIn": "Schon ein Konto? Anmelden",

  "onboarding.trialTitle": "7 Tage geschenkt",
  "onboarding.trialSub": "Alles freigeschaltet, ohne Kreditkarte.",
  "onboarding.perk1":
    "Fotografier deinen Kühlschrank — die App erkennt die Lebensmittel",
  "onboarding.perk2": "Der Wochenplan, gebaut aus dem, was du hast",
  "onboarding.perk3": "Die Einkaufsliste, ohne Doppeltes",
  "onboarding.go": "Los geht's",
  "onboarding.title": "Nur eine Frage",
  "onboarding.sub": "Damit wir dir nie etwas vorschlagen, das du nicht essen kannst.",
  "onboarding.diet": "Deine Ernährung",
  "onboarding.allergies": "Allergien?",
  "onboarding.otherAllergy": "Weitere Allergie (mit Komma trennen)",
  "onboarding.finish": "Kühlschrank scannen",
  "onboarding.editable": "Jederzeit in deinem Profil änderbar.",
  "onboarding.expired": "Sitzung abgelaufen, bitte neu anmelden.",

  "inventory.title": "Mein Kühlschrank",
  "inventory.empty": "Noch nichts da",
  "inventory.count": "{n} Lebensmittel",
  "inventory.countPlural": "{n} Lebensmittel",
  "inventory.emptyTitle": "Fang mit einem Foto an",
  "inventory.emptyBody":
    "Fotografier deinen Kühlschrank — wir erkennen die Lebensmittel für dich.",
  "inventory.scan": "Kühlschrank scannen",
  "inventory.analysing": "Foto wird ausgewertet…",
  "inventory.detected": "{n} Lebensmittel gefunden",
  "inventory.detectedPlural": "{n} Lebensmittel gefunden",
  "inventory.review": "Prüfen und korrigieren, dann hinzufügen.",
  "inventory.name": "Name",
  "inventory.qty": "Menge",
  "inventory.expiry": "Haltbar bis (JJJJ-MM-TT)",
  "inventory.expiryHint":
    "Geschätzte Haltbarkeit — korrigier sie, wenn du das echte Datum kennst.",
  "inventory.brand": "Marke (optional)",
  "inventory.addRow": "Artikel hinzufügen",
  "inventory.save": "Alles in den Kühlschrank",
  "inventory.doubtful": "prüfen",
  "inventory.urgent": "{n} Lebensmittel bald aufbrauchen",
  "inventory.urgentPlural": "{n} Lebensmittel bald aufbrauchen",
  "inventory.remove": "{name} aus dem Kühlschrank nehmen",
  "inventory.errScan": "Foto konnte nicht gelesen werden",
  "inventory.errSave": "Konnte nicht gespeichert werden",
  "inventory.errDelete": "Konnte nicht entfernt werden",
  "inventory.errAlerts": "Hinweise konnten nicht aktiviert werden",
  "inventory.alertsRefused":
    "Mitteilungen blockiert — aktivier sie in den Einstellungen.",

  "allergen.peanut": "Erdnuss",
  "allergen.nuts": "Schalenfrüchte",
  "allergen.lactose": "Laktose",
  "allergen.gluten": "Gluten",
  "allergen.egg": "Ei",
  "allergen.fish": "Fisch",
  "allergen.shellfish": "Krustentiere",
  "allergen.soy": "Soja",
  "allergen.add": "Allergie {name} hinzufügen",
  "allergen.rm": "Allergie {name} entfernen",

  "diet.omnivore": "Alles",
  "diet.vegetarian": "Vegetarisch",
  "diet.vegan": "Vegan",
  "diet.glutenfree": "Glutenfrei",

  "unit.piece": "Stück",

  "expiry.today": "heute aufbrauchen",
  "expiry.tomorrow": "morgen",
  "expiry.inDays": "in {n} Tagen",
  "expiry.yesterday": "gestern abgelaufen",
  "expiry.sinceDays": "seit {n} Tagen abgelaufen",

  "search.title": "Was koche ich heute?",
  "search.placeholder": "z. B. italienisch heute Abend, unter 20 Min…",
  "search.go": "Suchen",
  "search.run": "Suche starten",
  "search.searching": "Suche nach Rezepten…",
  "search.emptyTitle": "Sag mir, worauf du Lust hast",
  "search.emptyBody": "Ich schlage Rezepte mit dem vor, was du schon hast.",
  "search.noResult": "Kein Rezept gefunden",
  "search.rephrase": "Formulier es mal anders.",
  "search.writing": "Rezept wird geschrieben…",
  "search.ingredients": "Zutaten",
  "search.ingredientsShort": "Zutaten",
  "search.steps": "Zubereitung",
  "search.minutes": "Min",
  "search.servings": "Portionen",
  "search.keep": "Rezept merken",
  "search.kept": "Gemerkt",
  "search.savedHead": "Deine gemerkten Rezepte",
  "search.forget": "Nicht mehr merken",
  "search.errSearch": "Suche fehlgeschlagen",
  "search.errDetail": "Rezept konnte nicht geladen werden",
  "search.errKeep": "Rezept konnte nicht gemerkt werden",
  "search.errForget": "Konnte nicht entfernt werden",
  "search.forgetLabel": "{title} nicht mehr merken",
  "search.keptLabel": "{title} ist gemerkt",
  "inventory.removeLabel": "{name} aus dem Kühlschrank entfernen",
  "shopping.storeLabelOne": "1 Artikel in den Kühlschrank legen",
  "shopping.storeLabelMany": "{n} Artikel in den Kühlschrank legen",
  "cooked.keepLabel": "{name} behalten",
  "cooked.removeLabel": "{name} entfernen",
  "feedback.rateLabel": "Mit {n} von 5 bewerten",
  "premium.gateLabel": "Premium-Abo ansehen",
  "premium.gateCta": "Premium entdecken — {price} €/Monat",
  "search.keepLabel": "{title} speichern",
  "search.chip1": "Heute Abend schnell",
  "search.chip2": "Unter 20 Min",
  "search.chip3": "Vegetarisch",
  "search.chip4": "Aus meinem Kühlschrank",

  "plan.title": "Meine Woche",
  "plan.generating": "Dein Plan entsteht…",
  "plan.wait": "Etwa dreißig Sekunden.",
  "plan.emptyTitle": "Sieben Tage, null Fragen",
  "plan.emptyBody":
    "Ich baue deine Woche aus deinem Kühlschrank, deinem Budget und deiner Ernährung.",
  "plan.generate": "Woche planen",
  "plan.regenerate": "Woche neu planen",
  "plan.budget": "Budget für die Woche (optional)",
  "plan.budgetLabel": "Wochenbudget in Euro",
  "plan.cost": "Geschätzte Kosten: {cost} €",
  "plan.costBudget": "Geschätzte Kosten: {cost} € / Budget {budget} €",
  "plan.breakfast": "Frühstück",
  "plan.lunch": "Mittag",
  "plan.dinner": "Abendessen",
  "plan.snack": "Snack",
  "plan.noSteps": "Zubereitung nicht verfügbar.",
  "plan.errGenerate": "Plan konnte nicht erstellt werden",
  "plan.errSteps": "Zubereitung konnte nicht geladen werden",

  "shopping.title": "Mein Einkauf",
  "shopping.building": "Deine Liste entsteht…",
  "shopping.emptyTitle": "Nie wieder doppelt kaufen",
  "shopping.emptyBody":
    "Ich gehe von deinem Wochenplan aus und streiche, was du schon hast.",
  "shopping.generate": "Liste erstellen",
  "shopping.regenerate": "Liste neu erstellen",
  "shopping.estimate": "Schätzung",
  "shopping.checked": "Abgehakt",
  "shopping.inFridge": "Schon im Kühlschrank (bitte prüfen)",
  "shopping.readd": "+ hinzufügen",
  "shopping.store": "Einkauf erledigt ({n})",
  "shopping.storing": "Wird eingeräumt…",
  "shopping.stored": "{n} Artikel in den Kühlschrank gelegt",
  "shopping.storedPlural": "{n} Artikel in den Kühlschrank gelegt",
  "shopping.needPlan": "Erstell zuerst einen Wochenplan.",
  "shopping.errGenerate": "Liste konnte nicht erstellt werden",
  "shopping.errCheck": "Das Häkchen konnte nicht gespeichert werden.",
  "shopping.errStore": "Einkauf konnte nicht eingeräumt werden",
  "shopping.toSort": "Einzuordnen",
  "shopping.check": "{name} abhaken",
  "shopping.uncheck": "Häkchen bei {name} entfernen",

  "aisle.produce": "Obst und Gemüse",
  "aisle.dairy": "Molkereiprodukte",
  "aisle.meat": "Fleisch und Fisch",
  "aisle.grocery": "Trockenware",
  "aisle.frozen": "Tiefkühl",
  "aisle.bakery": "Backwaren",
  "aisle.other": "Sonstiges",

  "cooked.button": "Das habe ich gekocht",
  "cooked.label": "Dieses Rezept als gekocht markieren",
  "cooked.question": "Was ist aufgebraucht?",
  "cooked.remove": "Aus meinem Kühlschrank nehmen",
  "cooked.done": "Kühlschrank aktualisiert",
  "cooked.nothing": "Nichts zu entfernen",
  "cooked.readError": "Dein Kühlschrank konnte nicht gelesen werden",

  "profile.title": "Profil",
  "profile.budget": "Wochenbudget",
  "profile.timePerMeal": "Zeit pro Mahlzeit",
  "profile.diet": "Ernährung",
  "profile.goals": "Ziele",
  "profile.allergies": "Allergien",
  "profile.noAllergy": "keine",
  "profile.signOut": "Abmelden",
  "profile.signOutLabel": "Von der App abmelden",
  "profile.errSignOut": "Abmelden fehlgeschlagen",
  "profile.language": "Sprache",

  "premium.active": "Premium aktiv — danke!",
  "premium.upgrade": "Auf Premium wechseln",
  "premium.yourTrial": "Deine Testphase",
  "premium.perMonth": "/Monat",
  "premium.daysLeft": "Voller Zugang noch {n} Tage",
  "premium.lastDay": "Letzter Tag mit vollem Zugang",
  "premium.remaining": "Was dir diesen Monat bleibt.",
  "premium.scans": "Scans",
  "premium.searches": "Suchen",
  "premium.willLose": "Das verlierst du am Ende der Testphase",
  "premium.withPremium": "Mit Premium",
  "premium.perk1": "Der Wochenplan, 8 pro Monat",
  "premium.perk2": "Die Einkaufsliste, nach Regal sortiert",
  "premium.perk3": "100 Scans und 300 Suchen pro Monat",
  "premium.subscribe": "Abonnieren",
  "premium.keepAccess": "Vollen Zugang behalten",
  "premium.soon": "Die Bezahlung kommt bald.",
  "premium.errCheckout": "Bezahlseite konnte nicht geöffnet werden",
  "premium.discover": "Premium ansehen",
  "premium.planLocked":
    "Der Wochenplan baut deine sieben Tage aus deinem Kühlschrank, deinem Budget und deiner Ernährung. Er gehört zu Premium.",
  "premium.shoppingLocked":
    "Die Liste entsteht aus deinem Wochenplan, nach Regal sortiert und ohne das, was du schon hast. Sie gehört zu Premium, wie der Plan.",

  "feedback.open": "Rückmeldung geben",
  "feedback.openAgain": "Noch eine Rückmeldung",
  "feedback.label": "Rückmeldung zur App geben",
  "feedback.title": "Deine Rückmeldung",
  "feedback.hint": "Sei ehrlich — das hilft mehr als nett zu sein.",
  "feedback.liked": "Was hat dir gefallen?",
  "feedback.missing": "Was hat gefehlt oder genervt?",
  "feedback.rate": "{n} von 5 geben",
  "feedback.needRating": "Wähl eine Bewertung",
  "feedback.thanks": "Danke — notiert.",
  "feedback.errSend": "Senden fehlgeschlagen",

  "error.title": "Da ist etwas schiefgelaufen",
  "error.session": "Sitzung abgelaufen — bitte neu anmelden.",
  "error.unreachable": "Server nicht erreichbar. Versuch es gleich nochmal.",
  "error.server": "Der Server hat {code} geantwortet.",
};
