import type { Key } from "./index";

/** English. */
export const en: Record<Key, string> = {
  "common.cancel": "Cancel",
  "common.close": "Close",
  "common.delete": "Delete",
  "common.retry": "Try again",
  "common.later": "Later",
  "common.send": "Send",
  "common.continue": "Continue",
  "common.optional": "optional",

  "login.tagline": "Snap your fridge, we'll handle the rest.",
  "login.step1.title": "Snap your fridge",
  "login.step1.text":
    "The app spots your food and estimates how long it will keep.",
  "login.step2.title": "Get recipe ideas",
  "login.step2.text":
    "Made with what you already have, starting with what expires soonest.",
  "login.step3.title": "Stop buying doubles",
  "login.step3.text": "Your shopping list drops whatever is still in the fridge.",
  "login.start": "Start free",
  "login.reassure": "Nothing to install, no card needed.",
  "login.haveAccount": "I already have an account",
  "login.whatIsIt": "← What is SmartChef?",
  "login.email": "Email",
  "login.password": "Password",
  "login.signIn": "Sign in",
  "login.signUp": "Create account",
  "login.toSignUp": "No account yet? Create one",
  "login.toSignIn": "Already registered? Sign in",

  "onboarding.trialTitle": "7 days on us",
  "onboarding.trialSub": "Everything unlocked, no card needed.",
  "onboarding.perk1": "Snap your fridge and the app spots your food",
  "onboarding.perk2": "A full week of meals, built around what you have",
  "onboarding.perk3": "A shopping list that skips what you already own",
  "onboarding.go": "Let's go",
  "onboarding.title": "One question only",
  "onboarding.sub": "So we never suggest something you can't eat.",
  "onboarding.diet": "Your diet",
  "onboarding.allergies": "Any allergies?",
  "onboarding.otherAllergy": "Other allergy (comma separated)",
  "onboarding.finish": "Scan my fridge",
  "onboarding.editable": "You can change this anytime in your profile.",
  "onboarding.expired": "Session expired, please sign in again.",

  "inventory.title": "My fridge",
  "inventory.empty": "Nothing yet",
  "inventory.count": "{n} item",
  "inventory.countPlural": "{n} items",
  "inventory.emptyTitle": "Start with a photo",
  "inventory.emptyBody": "Snap your fridge and we'll identify the food for you.",
  "inventory.scan": "Scan my fridge",
  "inventory.analysing": "Reading the photo…",
  "inventory.detected": "{n} item found",
  "inventory.detectedPlural": "{n} items found",
  "inventory.review": "Check and fix before adding.",
  "inventory.name": "Name",
  "inventory.qty": "Qty",
  "inventory.expiry": "Use-by date (YYYY-MM-DD)",
  "inventory.expiryHint": "Estimated shelf life — correct it if you know the real date.",
  "inventory.brand": "Brand (optional)",
  "inventory.addRow": "Add an item",
  "inventory.save": "Add all to my fridge",
  "inventory.doubtful": "check this",
  "inventory.urgent": "{n} item to eat soon",
  "inventory.urgentPlural": "{n} items to eat soon",
  "inventory.remove": "Remove {name} from the fridge",
  "inventory.errScan": "Could not read the photo",
  "inventory.errSave": "Could not save",
  "inventory.errDelete": "Could not remove it",
  "inventory.errAlerts": "Could not turn alerts on",
  "inventory.alertsRefused": "Notifications blocked — turn them on in your settings.",

  "allergen.peanut": "Peanut",
  "allergen.nuts": "Tree nuts",
  "allergen.lactose": "Lactose",
  "allergen.gluten": "Gluten",
  "allergen.egg": "Egg",
  "allergen.fish": "Fish",
  "allergen.shellfish": "Shellfish",
  "allergen.soy": "Soy",
  "allergen.add": "Add the {name} allergy",
  "allergen.rm": "Remove the {name} allergy",

  "diet.omnivore": "Omnivore",
  "diet.vegetarian": "Vegetarian",
  "diet.vegan": "Vegan",
  "diet.glutenfree": "Gluten free",

  "unit.piece": "piece",

  "expiry.today": "eat it today",
  "expiry.tomorrow": "tomorrow",
  "expiry.inDays": "in {n} days",
  "expiry.yesterday": "expired yesterday",
  "expiry.sinceDays": "expired {n} days ago",

  "search.title": "What am I cooking?",
  "search.placeholder": "e.g. italian tonight, under 20 min…",
  "search.go": "Search",
  "search.run": "Run the search",
  "search.searching": "Looking for recipes…",
  "search.emptyTitle": "Tell me what you fancy",
  "search.emptyBody": "I'll suggest recipes using what you already have.",
  "search.noResult": "No recipe found",
  "search.rephrase": "Try wording it differently.",
  "search.writing": "Writing the recipe…",
  "search.ingredients": "Ingredients",
  "search.ingredientsShort": "ingredients",
  "search.steps": "Method",
  "search.minutes": "min",
  "search.servings": "servings",
  "search.keep": "Keep this recipe",
  "search.kept": "Kept",
  "search.savedHead": "Your kept recipes",
  "search.forget": "Stop keeping it",
  "search.errSearch": "Search failed",
  "search.errDetail": "Could not load the recipe",
  "search.errKeep": "Could not keep this recipe",
  "search.errForget": "Could not remove it",
  "search.forgetLabel": "Stop keeping {title}",
  "search.keptLabel": "{title} is kept",
  "inventory.removeLabel": "Remove {name} from your fridge",
  "shopping.storeLabelOne": "Put 1 item in the fridge",
  "shopping.storeLabelMany": "Put {n} items in the fridge",
  "cooked.keepLabel": "Keep {name}",
  "cooked.removeLabel": "Remove {name}",
  "feedback.rateLabel": "Rate {n} out of 5",
  "premium.gateLabel": "See the Premium plan",
  "premium.gateCta": "Discover Premium — €{price}/month",
  "search.keepLabel": "Save {title}",
  "search.chip1": "Quick tonight",
  "search.chip2": "Under 20 min",
  "search.chip3": "Vegetarian",
  "search.chip4": "From my fridge",

  "plan.title": "My week",
  "plan.generating": "Building your plan…",
  "plan.wait": "About thirty seconds.",
  "plan.emptyTitle": "Seven days, no questions",
  "plan.emptyBody":
    "I'll build your week from your fridge, your budget and your diet.",
  "plan.generate": "Build my week",
  "plan.regenerate": "Rebuild the week",
  "plan.budget": "Budget for the week (optional)",
  "plan.budgetLabel": "Weekly budget in euros",
  "plan.cost": "Estimated cost: €{cost}",
  "plan.costBudget": "Estimated cost: €{cost} / budget €{budget}",
  "plan.breakfast": "Breakfast",
  "plan.lunch": "Lunch",
  "plan.dinner": "Dinner",
  "plan.snack": "Snack",
  "plan.noSteps": "Method not available.",
  "plan.errGenerate": "Could not build the plan",
  "plan.errSteps": "Could not load the method",

  "shopping.title": "My shopping",
  "shopping.building": "Building your list…",
  "shopping.emptyTitle": "Never buy doubles again",
  "shopping.emptyBody":
    "I start from your meal plan and drop what you already have.",
  "shopping.generate": "Build the list",
  "shopping.regenerate": "Rebuild the list",
  "shopping.estimate": "Estimate",
  "shopping.checked": "Ticked",
  "shopping.inFridge": "Already in your fridge (worth checking)",
  "shopping.readd": "+ add",
  "shopping.store": "I've done the shopping ({n})",
  "shopping.storing": "Putting away…",
  "shopping.stored": "{n} item added to your fridge",
  "shopping.storedPlural": "{n} items added to your fridge",
  "shopping.needPlan": "Build a meal plan first.",
  "shopping.errGenerate": "Could not build the list",
  "shopping.errCheck": "That tick could not be saved.",
  "shopping.errStore": "Could not put the shopping away",
  "shopping.toSort": "To sort",
  "shopping.check": "Tick {name}",
  "shopping.uncheck": "Untick {name}",

  "aisle.produce": "Fruit and veg",
  "aisle.dairy": "Dairy",
  "aisle.meat": "Meat and fish",
  "aisle.grocery": "Groceries",
  "aisle.frozen": "Frozen",
  "aisle.bakery": "Bakery",
  "aisle.other": "Other",

  "cooked.button": "I cooked this",
  "cooked.label": "Mark this recipe as cooked",
  "cooked.question": "What did you finish?",
  "cooked.remove": "Remove from my fridge",
  "cooked.done": "Fridge updated",
  "cooked.nothing": "Nothing to remove",
  "cooked.readError": "Couldn't read your fridge",

  "profile.title": "Profile",
  "profile.budget": "Weekly budget",
  "profile.timePerMeal": "Time per meal",
  "profile.diet": "Diet",
  "profile.goals": "Goals",
  "profile.allergies": "Allergies",
  "profile.noAllergy": "none",
  "profile.signOut": "Sign out",
  "profile.signOutLabel": "Sign out of the app",
  "profile.errSignOut": "Could not sign out",
  "profile.language": "Language",

  "premium.active": "Premium active — thank you!",
  "premium.upgrade": "Go Premium",
  "premium.yourTrial": "Your trial",
  "premium.perMonth": "/month",
  "premium.daysLeft": "Full access for {n} more days",
  "premium.lastDay": "Last day of full access",
  "premium.remaining": "What's left this month.",
  "premium.scans": "scans",
  "premium.searches": "searches",
  "premium.willLose": "What you'll lose when the trial ends",
  "premium.withPremium": "With Premium",
  "premium.perk1": "The weekly plan, 8 per month",
  "premium.perk2": "The shopping list, sorted by aisle",
  "premium.perk3": "100 scans and 300 searches a month",
  "premium.subscribe": "Subscribe",
  "premium.keepAccess": "Keep full access",
  "premium.soon": "Payment is coming soon.",
  "premium.errCheckout": "Could not open the payment page",
  "premium.discover": "See Premium",
  "premium.planLocked":
    "The weekly plan builds your seven days from your fridge, your budget and your diet. It's part of Premium.",
  "premium.shoppingLocked":
    "The list is built from your meal plan, sorted by aisle, minus what you already have. It's part of Premium, like the plan.",

  "feedback.open": "Leave feedback",
  "feedback.openAgain": "Leave more feedback",
  "feedback.label": "Leave feedback about the app",
  "feedback.title": "Your feedback",
  "feedback.hint": "Be blunt — it helps more than being nice.",
  "feedback.liked": "What did you like?",
  "feedback.missing": "What was missing or annoying?",
  "feedback.rate": "Rate it {n} out of 5",
  "feedback.needRating": "Pick a rating",
  "feedback.thanks": "Thank you — noted.",
  "feedback.errSend": "Could not send",

  "error.title": "Something went wrong",
  "error.session": "Session expired — please sign in again.",
  "error.unreachable": "Can't reach the server. Try again in a moment.",
  "error.server": "The server replied {code}.",
};
