import type { Key } from "./index";

/** Español. */
export const es: Record<Key, string> = {
  "common.cancel": "Cancelar",
  "common.close": "Cerrar",
  "common.delete": "Eliminar",
  "common.retry": "Reintentar",
  "common.later": "Más tarde",
  "common.send": "Enviar",
  "common.continue": "Continuar",
  "common.optional": "opcional",

  "login.tagline": "Haz una foto a tu nevera, del resto nos ocupamos nosotros.",
  "login.step1.title": "Fotografía tu nevera",
  "login.step1.text":
    "La app reconoce los alimentos y calcula cuánto tiempo aguantan.",
  "login.step2.title": "Recibe recetas",
  "login.step2.text":
    "Ideas con lo que ya tienes, empezando por lo que caduca antes.",
  "login.step3.title": "No compres cosas repetidas",
  "login.step3.text": "La lista de la compra quita lo que sigue en tu nevera.",
  "login.start": "Empezar gratis",
  "login.reassure": "Sin instalar nada, sin tarjeta.",
  "login.haveAccount": "Ya tengo cuenta",
  "login.whatIsIt": "← ¿Qué es SmartChef?",
  "login.email": "Correo",
  "login.password": "Contraseña",
  "login.signIn": "Entrar",
  "login.signUp": "Crear cuenta",
  "login.toSignUp": "¿Sin cuenta? Crea una",
  "login.toSignIn": "¿Ya tienes cuenta? Entra",

  "onboarding.trialTitle": "7 días gratis",
  "onboarding.trialSub": "Todo abierto, sin tarjeta.",
  "onboarding.perk1": "Fotografía tu nevera y la app reconoce los alimentos",
  "onboarding.perk2": "El menú semanal, hecho con lo que tienes",
  "onboarding.perk3": "La lista de la compra, sin repetir lo que ya tienes",
  "onboarding.go": "Vamos allá",
  "onboarding.title": "Una sola pregunta",
  "onboarding.sub": "Para no proponerte nunca algo que no puedas comer.",
  "onboarding.diet": "Tu dieta",
  "onboarding.allergies": "¿Alguna alergia?",
  "onboarding.otherAllergy": "Otra alergia (separadas por comas)",
  "onboarding.finish": "Escanear mi nevera",
  "onboarding.editable": "Puedes cambiarlo cuando quieras en tu perfil.",
  "onboarding.expired": "Sesión caducada, vuelve a entrar.",

  "inventory.title": "Mi nevera",
  "inventory.empty": "Nada por ahora",
  "inventory.count": "{n} alimento",
  "inventory.countPlural": "{n} alimentos",
  "inventory.emptyTitle": "Empieza con una foto",
  "inventory.emptyBody":
    "Haz una foto a tu nevera y identificamos los alimentos por ti.",
  "inventory.scan": "Escanear mi nevera",
  "inventory.analysing": "Analizando la foto…",
  "inventory.detected": "{n} alimento detectado",
  "inventory.detectedPlural": "{n} alimentos detectados",
  "inventory.review": "Revisa y corrige antes de añadir.",
  "inventory.name": "Nombre",
  "inventory.qty": "Cant.",
  "inventory.expiry": "Fecha de caducidad (AAAA-MM-DD)",
  "inventory.expiryHint":
    "Conservación estimada — corrígela si sabes la fecha real.",
  "inventory.brand": "Marca (opcional)",
  "inventory.addRow": "Añadir un artículo",
  "inventory.save": "Añadir todo a mi nevera",
  "inventory.doubtful": "revisar",
  "inventory.urgent": "{n} alimento para consumir pronto",
  "inventory.urgentPlural": "{n} alimentos para consumir pronto",
  "inventory.remove": "Quitar {name} de la nevera",
  "inventory.errScan": "No se pudo leer la foto",
  "inventory.errSave": "No se pudo guardar",
  "inventory.errDelete": "No se pudo eliminar",
  "inventory.errAlerts": "No se pudieron activar los avisos",
  "inventory.alertsRefused":
    "Notificaciones bloqueadas — actívalas en los ajustes.",

  "allergen.peanut": "Cacahuete",
  "allergen.nuts": "Frutos secos",
  "allergen.lactose": "Lactosa",
  "allergen.gluten": "Gluten",
  "allergen.egg": "Huevo",
  "allergen.fish": "Pescado",
  "allergen.shellfish": "Marisco",
  "allergen.soy": "Soja",
  "allergen.add": "Añadir la alergia {name}",
  "allergen.rm": "Quitar la alergia {name}",

  "diet.omnivore": "Omnívora",
  "diet.vegetarian": "Vegetariana",
  "diet.vegan": "Vegana",
  "diet.glutenfree": "Sin gluten",

  "unit.piece": "unidad",

  "expiry.today": "cómetelo hoy",
  "expiry.tomorrow": "mañana",
  "expiry.inDays": "en {n} días",
  "expiry.yesterday": "caducó ayer",
  "expiry.sinceDays": "caducó hace {n} días",

  "search.title": "¿Qué cocino hoy?",
  "search.placeholder": "ej. italiano esta noche, menos de 20 min…",
  "search.go": "Buscar",
  "search.run": "Lanzar la búsqueda",
  "search.searching": "Buscando recetas…",
  "search.emptyTitle": "Dime qué te apetece",
  "search.emptyBody": "Te propongo recetas con lo que ya tienes.",
  "search.noResult": "Ninguna receta encontrada",
  "search.rephrase": "Prueba a decirlo de otra forma.",
  "search.writing": "Escribiendo la receta…",
  "search.ingredients": "Ingredientes",
  "search.ingredientsShort": "ingredientes",
  "search.steps": "Preparación",
  "search.minutes": "min",
  "search.servings": "raciones",
  "search.keep": "Guardar esta receta",
  "search.kept": "Guardada",
  "search.savedHead": "Tus recetas guardadas",
  "search.forget": "Dejar de guardarla",
  "search.errSearch": "La búsqueda ha fallado",
  "search.errDetail": "No se pudo cargar la receta",
  "search.errKeep": "No se pudo guardar esta receta",
  "search.errForget": "No se pudo eliminar",
  "search.forgetLabel": "Dejar de guardar {title}",
  "search.keptLabel": "{title} está guardada",
  "search.chip1": "Rápido esta noche",
  "search.chip2": "Menos de 20 min",
  "search.chip3": "Vegetariano",
  "search.chip4": "Con mi nevera",

  "plan.title": "Mi semana",
  "plan.generating": "Creando tu menú…",
  "plan.wait": "Unos treinta segundos.",
  "plan.emptyTitle": "Siete días, cero preguntas",
  "plan.emptyBody":
    "Preparo tu semana a partir de tu nevera, tu presupuesto y tu dieta.",
  "plan.generate": "Crear mi semana",
  "plan.regenerate": "Rehacer la semana",
  "plan.budget": "Presupuesto de la semana (opcional)",
  "plan.budgetLabel": "Presupuesto semanal en euros",
  "plan.cost": "Coste estimado: {cost} €",
  "plan.costBudget": "Coste estimado: {cost} € / presupuesto {budget} €",
  "plan.breakfast": "Desayuno",
  "plan.lunch": "Comida",
  "plan.dinner": "Cena",
  "plan.snack": "Merienda",
  "plan.noSteps": "Preparación no disponible.",
  "plan.errGenerate": "No se pudo crear el menú",
  "plan.errSteps": "No se pudo cargar la preparación",

  "shopping.title": "Mi compra",
  "shopping.building": "Creando tu lista…",
  "shopping.emptyTitle": "No compres cosas repetidas",
  "shopping.emptyBody":
    "Parto de tu menú semanal y quito lo que ya tienes.",
  "shopping.generate": "Crear la lista",
  "shopping.regenerate": "Rehacer la lista",
  "shopping.estimate": "Estimación",
  "shopping.checked": "Marcados",
  "shopping.inFridge": "Ya en tu nevera (conviene revisarlo)",
  "shopping.readd": "+ añadir",
  "shopping.store": "Ya he hecho la compra ({n})",
  "shopping.storing": "Guardando…",
  "shopping.stored": "{n} artículo añadido a tu nevera",
  "shopping.storedPlural": "{n} artículos añadidos a tu nevera",
  "shopping.needPlan": "Crea antes un menú semanal.",
  "shopping.errGenerate": "No se pudo crear la lista",
  "shopping.errCheck": "No se pudo guardar la marca.",
  "shopping.errStore": "No se pudo guardar la compra",
  "shopping.toSort": "Por clasificar",
  "shopping.check": "Marcar {name}",
  "shopping.uncheck": "Desmarcar {name}",

  "aisle.produce": "Frutas y verduras",
  "aisle.dairy": "Lácteos",
  "aisle.meat": "Carne y pescado",
  "aisle.grocery": "Despensa",
  "aisle.frozen": "Congelados",
  "aisle.bakery": "Panadería",
  "aisle.other": "Otros",

  "cooked.button": "Lo he cocinado",
  "cooked.label": "Marcar esta receta como cocinada",
  "cooked.question": "¿Qué has terminado?",
  "cooked.remove": "Quitar de mi nevera",
  "cooked.done": "Nevera actualizada",
  "cooked.nothing": "Nada que quitar",
  "cooked.readError": "No se pudo leer tu nevera",

  "profile.title": "Perfil",
  "profile.budget": "Presupuesto semanal",
  "profile.timePerMeal": "Tiempo por comida",
  "profile.diet": "Dieta",
  "profile.goals": "Objetivos",
  "profile.allergies": "Alergias",
  "profile.noAllergy": "ninguna",
  "profile.signOut": "Cerrar sesión",
  "profile.signOutLabel": "Cerrar sesión en la app",
  "profile.errSignOut": "No se pudo cerrar la sesión",
  "profile.language": "Idioma",

  "premium.active": "Premium activo — ¡gracias!",
  "premium.upgrade": "Pasar a Premium",
  "premium.yourTrial": "Tu prueba",
  "premium.perMonth": "/mes",
  "premium.daysLeft": "Acceso completo {n} días más",
  "premium.lastDay": "Último día de acceso completo",
  "premium.remaining": "Lo que te queda este mes.",
  "premium.scans": "escaneos",
  "premium.searches": "búsquedas",
  "premium.willLose": "Lo que perderás al acabar la prueba",
  "premium.withPremium": "Con Premium",
  "premium.perk1": "El menú semanal, 8 al mes",
  "premium.perk2": "La lista de la compra, por secciones",
  "premium.perk3": "100 escaneos y 300 búsquedas al mes",
  "premium.subscribe": "Suscribirme",
  "premium.keepAccess": "Mantener el acceso completo",
  "premium.soon": "El pago llega pronto.",
  "premium.errCheckout": "No se pudo abrir la página de pago",
  "premium.discover": "Ver Premium",
  "premium.planLocked":
    "El menú semanal prepara tus siete días a partir de tu nevera, tu presupuesto y tu dieta. Forma parte de Premium.",
  "premium.shoppingLocked":
    "La lista se crea a partir de tu menú semanal, ordenada por secciones y sin lo que ya tienes. Forma parte de Premium, igual que el menú.",

  "feedback.open": "Dar mi opinión",
  "feedback.openAgain": "Dar otra opinión",
  "feedback.label": "Dar mi opinión sobre la app",
  "feedback.title": "Tu opinión",
  "feedback.hint": "Sé sincero, ayuda más que ser amable.",
  "feedback.liked": "¿Qué te ha gustado?",
  "feedback.missing": "¿Qué te ha faltado o molestado?",
  "feedback.rate": "Puntuar con {n} sobre 5",
  "feedback.needRating": "Elige una puntuación",
  "feedback.thanks": "Gracias — tomo nota.",
  "feedback.errSend": "No se pudo enviar",

  "error.title": "Algo ha salido mal",
  "error.session": "Sesión caducada — vuelve a entrar.",
  "error.unreachable": "No se puede contactar con el servidor. Inténtalo en un momento.",
  "error.server": "El servidor ha respondido {code}.",
};
