import type { Key } from "./index";

/** Italiano. */
export const it: Record<Key, string> = {
  "common.cancel": "Annulla",
  "common.close": "Chiudi",
  "common.delete": "Elimina",
  "common.retry": "Riprova",
  "common.later": "Più tardi",
  "common.send": "Invia",
  "common.continue": "Continua",
  "common.optional": "facoltativo",

  "login.tagline": "Fotografa il frigo, al resto pensiamo noi.",
  "login.step1.title": "Fotografa il frigo",
  "login.step1.text":
    "L'app riconosce gli alimenti e stima quanto durano.",
  "login.step2.title": "Ricevi delle ricette",
  "login.step2.text":
    "Idee con quello che hai già, partendo da ciò che scade prima.",
  "login.step3.title": "Non comprare doppioni",
  "login.step3.text": "La lista della spesa toglie quello che hai ancora in frigo.",
  "login.start": "Inizia gratis",
  "login.reassure": "Niente da installare, nessuna carta.",
  "login.haveAccount": "Ho già un account",
  "login.whatIsIt": "← Cos'è SmartChef?",
  "login.email": "Email",
  "login.password": "Password",
  "login.signIn": "Accedi",
  "login.signUp": "Crea un account",
  "login.toSignUp": "Non hai un account? Creane uno",
  "login.toSignIn": "Hai già un account? Accedi",

  "onboarding.trialTitle": "7 giorni offerti",
  "onboarding.trialSub": "Tutto sbloccato, nessuna carta.",
  "onboarding.perk1": "Fotografa il frigo e l'app riconosce gli alimenti",
  "onboarding.perk2": "Il menù della settimana, costruito con quello che hai",
  "onboarding.perk3": "La lista della spesa, senza ricomprare ciò che hai",
  "onboarding.go": "Si parte",
  "onboarding.title": "Una sola domanda",
  "onboarding.sub": "Per non proporti mai qualcosa che non puoi mangiare.",
  "onboarding.diet": "La tua dieta",
  "onboarding.allergies": "Allergie?",
  "onboarding.otherAllergy": "Altra allergia (separate da virgola)",
  "onboarding.finish": "Scansiona il frigo",
  "onboarding.editable": "Puoi modificarlo quando vuoi nel tuo profilo.",
  "onboarding.expired": "Sessione scaduta, accedi di nuovo.",

  "inventory.title": "Il mio frigo",
  "inventory.empty": "Ancora niente",
  "inventory.count": "{n} alimento",
  "inventory.countPlural": "{n} alimenti",
  "inventory.emptyTitle": "Inizia con una foto",
  "inventory.emptyBody":
    "Fotografa il frigo e identifichiamo gli alimenti per te.",
  "inventory.scan": "Scansiona il frigo",
  "inventory.analysing": "Analisi della foto…",
  "inventory.detected": "{n} alimento trovato",
  "inventory.detectedPlural": "{n} alimenti trovati",
  "inventory.review": "Controlla e correggi prima di aggiungere.",
  "inventory.name": "Nome",
  "inventory.qty": "Qtà",
  "inventory.expiry": "Data di scadenza (AAAA-MM-GG)",
  "inventory.expiryHint":
    "Conservazione stimata — correggila se conosci la data reale.",
  "inventory.brand": "Marca (facoltativo)",
  "inventory.addRow": "Aggiungi un articolo",
  "inventory.save": "Aggiungi tutto al frigo",
  "inventory.doubtful": "da controllare",
  "inventory.urgent": "{n} alimento da consumare presto",
  "inventory.urgentPlural": "{n} alimenti da consumare presto",
  "inventory.remove": "Togli {name} dal frigo",
  "inventory.errScan": "Impossibile leggere la foto",
  "inventory.errSave": "Impossibile salvare",
  "inventory.errDelete": "Impossibile rimuovere",
  "inventory.errAlerts": "Impossibile attivare gli avvisi",
  "inventory.alertsRefused":
    "Notifiche bloccate — attivale nelle impostazioni.",

  "allergen.peanut": "Arachidi",
  "allergen.nuts": "Frutta a guscio",
  "allergen.lactose": "Lattosio",
  "allergen.gluten": "Glutine",
  "allergen.egg": "Uovo",
  "allergen.fish": "Pesce",
  "allergen.shellfish": "Crostacei",
  "allergen.soy": "Soia",
  "allergen.add": "Aggiungi l'allergia {name}",
  "allergen.rm": "Togli l'allergia {name}",

  "diet.omnivore": "Onnivora",
  "diet.vegetarian": "Vegetariana",
  "diet.vegan": "Vegana",
  "diet.glutenfree": "Senza glutine",

  "unit.piece": "pezzo",

  "expiry.today": "da mangiare oggi",
  "expiry.tomorrow": "domani",
  "expiry.inDays": "tra {n} giorni",
  "expiry.yesterday": "scaduto ieri",
  "expiry.sinceDays": "scaduto da {n} giorni",

  "search.title": "Cosa cucino oggi?",
  "search.placeholder": "es. italiano stasera, meno di 20 min…",
  "search.go": "Cerca",
  "search.run": "Avvia la ricerca",
  "search.searching": "Cerco delle ricette…",
  "search.emptyTitle": "Dimmi cosa ti va",
  "search.emptyBody": "Ti propongo ricette con quello che hai già.",
  "search.noResult": "Nessuna ricetta trovata",
  "search.rephrase": "Prova a dirlo in un altro modo.",
  "search.writing": "Scrivo la ricetta…",
  "search.ingredients": "Ingredienti",
  "search.ingredientsShort": "ingredienti",
  "search.steps": "Preparazione",
  "search.minutes": "min",
  "search.servings": "porzioni",
  "search.keep": "Salva questa ricetta",
  "search.kept": "Salvata",
  "search.savedHead": "Le tue ricette salvate",
  "search.forget": "Non salvarla più",
  "search.errSearch": "Ricerca fallita",
  "search.errDetail": "Impossibile caricare la ricetta",
  "search.errKeep": "Impossibile salvare questa ricetta",
  "search.errForget": "Impossibile rimuovere",
  "search.forgetLabel": "Smetti di salvare {title}",
  "search.keptLabel": "{title} è salvata",
  "search.chip1": "Veloce stasera",
  "search.chip2": "Meno di 20 min",
  "search.chip3": "Vegetariano",
  "search.chip4": "Con il mio frigo",

  "plan.title": "La mia settimana",
  "plan.generating": "Preparo il tuo menù…",
  "plan.wait": "Una trentina di secondi.",
  "plan.emptyTitle": "Sette giorni, zero domande",
  "plan.emptyBody":
    "Compongo la tua settimana partendo dal frigo, dal budget e dalla dieta.",
  "plan.generate": "Crea la mia settimana",
  "plan.regenerate": "Rifai la settimana",
  "plan.budget": "Budget della settimana (facoltativo)",
  "plan.budgetLabel": "Budget settimanale in euro",
  "plan.cost": "Costo stimato: {cost} €",
  "plan.costBudget": "Costo stimato: {cost} € / budget {budget} €",
  "plan.breakfast": "Colazione",
  "plan.lunch": "Pranzo",
  "plan.dinner": "Cena",
  "plan.snack": "Spuntino",
  "plan.noSteps": "Preparazione non disponibile.",
  "plan.errGenerate": "Impossibile creare il menù",
  "plan.errSteps": "Impossibile caricare la preparazione",

  "shopping.title": "La mia spesa",
  "shopping.building": "Preparo la tua lista…",
  "shopping.emptyTitle": "Mai più doppioni",
  "shopping.emptyBody":
    "Parto dal tuo menù e tolgo quello che hai già.",
  "shopping.generate": "Crea la lista",
  "shopping.regenerate": "Rifai la lista",
  "shopping.estimate": "Stima",
  "shopping.checked": "Segnati",
  "shopping.inFridge": "Già nel tuo frigo (meglio controllare)",
  "shopping.readd": "+ aggiungi",
  "shopping.store": "Ho fatto la spesa ({n})",
  "shopping.storing": "Metto via…",
  "shopping.stored": "{n} articolo aggiunto al frigo",
  "shopping.storedPlural": "{n} articoli aggiunti al frigo",
  "shopping.needPlan": "Crea prima un menù della settimana.",
  "shopping.errGenerate": "Impossibile creare la lista",
  "shopping.errCheck": "Non è stato possibile salvare la spunta.",
  "shopping.errStore": "Impossibile mettere via la spesa",
  "shopping.toSort": "Da sistemare",
  "shopping.check": "Segna {name}",
  "shopping.uncheck": "Togli la spunta a {name}",

  "aisle.produce": "Frutta e verdura",
  "aisle.dairy": "Latticini",
  "aisle.meat": "Carne e pesce",
  "aisle.grocery": "Dispensa",
  "aisle.frozen": "Surgelati",
  "aisle.bakery": "Panetteria",
  "aisle.other": "Altro",

  "cooked.button": "L'ho cucinato",
  "cooked.label": "Segna questa ricetta come cucinata",
  "cooked.question": "Cosa hai finito?",
  "cooked.remove": "Togli dal mio frigo",
  "cooked.done": "Frigo aggiornato",
  "cooked.nothing": "Niente da togliere",
  "cooked.readError": "Impossibile leggere il tuo frigo",

  "profile.title": "Profilo",
  "profile.budget": "Budget settimanale",
  "profile.timePerMeal": "Tempo per pasto",
  "profile.diet": "Dieta",
  "profile.goals": "Obiettivi",
  "profile.allergies": "Allergie",
  "profile.noAllergy": "nessuna",
  "profile.signOut": "Esci",
  "profile.signOutLabel": "Esci dall'applicazione",
  "profile.errSignOut": "Impossibile uscire",
  "profile.language": "Lingua",

  "premium.active": "Premium attivo — grazie!",
  "premium.upgrade": "Passa a Premium",
  "premium.yourTrial": "La tua prova",
  "premium.perMonth": "/mese",
  "premium.daysLeft": "Accesso completo per altri {n} giorni",
  "premium.lastDay": "Ultimo giorno di accesso completo",
  "premium.remaining": "Quello che ti resta questo mese.",
  "premium.scans": "scansioni",
  "premium.searches": "ricerche",
  "premium.willLose": "Cosa perderai alla fine della prova",
  "premium.withPremium": "Con Premium",
  "premium.perk1": "Il menù della settimana, 8 al mese",
  "premium.perk2": "La lista della spesa, per reparto",
  "premium.perk3": "100 scansioni e 300 ricerche al mese",
  "premium.subscribe": "Abbonati",
  "premium.keepAccess": "Mantieni l'accesso completo",
  "premium.soon": "Il pagamento arriva presto.",
  "premium.errCheckout": "Impossibile aprire il pagamento",
  "premium.discover": "Scopri Premium",
  "premium.planLocked":
    "Il menù della settimana compone i tuoi sette giorni partendo dal frigo, dal budget e dalla dieta. Fa parte di Premium.",
  "premium.shoppingLocked":
    "La lista nasce dal tuo menù, ordinata per reparto e senza quello che hai già. Fa parte di Premium, come il menù.",

  "feedback.open": "Lascia un parere",
  "feedback.openAgain": "Lascia un altro parere",
  "feedback.label": "Lascia un parere sull'applicazione",
  "feedback.title": "Il tuo parere",
  "feedback.hint": "Sii sincero, aiuta più che essere gentile.",
  "feedback.liked": "Cosa ti è piaciuto?",
  "feedback.missing": "Cosa è mancato o ti ha dato fastidio?",
  "feedback.rate": "Dai {n} su 5",
  "feedback.needRating": "Scegli un voto",
  "feedback.thanks": "Grazie — annotato.",
  "feedback.errSend": "Invio non riuscito",

  "error.title": "Qualcosa è andato storto",
  "error.session": "Sessione scaduta — accedi di nuovo.",
  "error.unreachable": "Impossibile contattare il server. Riprova tra poco.",
  "error.server": "Il server ha risposto {code}.",
};
