import type { Key } from "./index";

/** Português (Brasil). */
export const pt: Record<Key, string> = {
  "common.cancel": "Cancelar",
  "common.close": "Fechar",
  "common.delete": "Excluir",
  "common.retry": "Tentar de novo",
  "common.later": "Mais tarde",
  "common.send": "Enviar",
  "common.continue": "Continuar",
  "common.optional": "opcional",

  "login.tagline": "Fotografe sua geladeira, o resto é com a gente.",
  "login.step1.title": "Fotografe sua geladeira",
  "login.step1.text":
    "O app reconhece os alimentos e estima quanto tempo eles duram.",
  "login.step2.title": "Receba receitas",
  "login.step2.text":
    "Ideias com o que você já tem, começando pelo que vence primeiro.",
  "login.step3.title": "Não compre nada repetido",
  "login.step3.text": "A lista de compras tira o que ainda está na geladeira.",
  "login.start": "Começar de graça",
  "login.reassure": "Sem instalar nada, sem cartão.",
  "login.haveAccount": "Já tenho conta",
  "login.whatIsIt": "← O que é o SmartChef?",
  "login.email": "E-mail",
  "login.password": "Senha",
  "login.signIn": "Entrar",
  "login.signUp": "Criar conta",
  "login.toSignUp": "Sem conta? Crie uma",
  "login.toSignIn": "Já tem conta? Entre",

  "onboarding.trialTitle": "7 dias grátis",
  "onboarding.trialSub": "Tudo liberado, sem cartão.",
  "onboarding.perk1": "Fotografe sua geladeira e o app reconhece os alimentos",
  "onboarding.perk2": "O cardápio da semana, montado com o que você tem",
  "onboarding.perk3": "A lista de compras, sem repetir o que você já tem",
  "onboarding.go": "Vamos lá",
  "onboarding.title": "Uma única pergunta",
  "onboarding.sub": "Para nunca sugerir algo que você não pode comer.",
  "onboarding.diet": "Sua dieta",
  "onboarding.allergies": "Alguma alergia?",
  "onboarding.otherAllergy": "Outra alergia (separadas por vírgula)",
  "onboarding.finish": "Escanear minha geladeira",
  "onboarding.editable": "Dá para mudar quando quiser no seu perfil.",
  "onboarding.expired": "Sessão expirada, entre de novo.",

  "inventory.title": "Minha geladeira",
  "inventory.empty": "Nada por enquanto",
  "inventory.count": "{n} alimento",
  "inventory.countPlural": "{n} alimentos",
  "inventory.emptyTitle": "Comece com uma foto",
  "inventory.emptyBody":
    "Fotografe sua geladeira e identificamos os alimentos para você.",
  "inventory.scan": "Escanear minha geladeira",
  "inventory.analysing": "Analisando a foto…",
  "inventory.detected": "{n} alimento encontrado",
  "inventory.detectedPlural": "{n} alimentos encontrados",
  "inventory.review": "Confira e corrija antes de adicionar.",
  "inventory.name": "Nome",
  "inventory.qty": "Qtd.",
  "inventory.expiry": "Data de validade (AAAA-MM-DD)",
  "inventory.expiryHint":
    "Validade estimada — corrija se souber a data real.",
  "inventory.brand": "Marca (opcional)",
  "inventory.addRow": "Adicionar um item",
  "inventory.save": "Adicionar tudo à geladeira",
  "inventory.doubtful": "conferir",
  "inventory.urgent": "{n} alimento para consumir logo",
  "inventory.urgentPlural": "{n} alimentos para consumir logo",
  "inventory.remove": "Tirar {name} da geladeira",
  "inventory.errScan": "Não foi possível ler a foto",
  "inventory.errSave": "Não foi possível salvar",
  "inventory.errDelete": "Não foi possível remover",
  "inventory.errAlerts": "Não foi possível ativar os avisos",
  "inventory.alertsRefused":
    "Notificações bloqueadas — ative nas configurações.",

  "allergen.peanut": "Amendoim",
  "allergen.nuts": "Castanhas",
  "allergen.lactose": "Lactose",
  "allergen.gluten": "Glúten",
  "allergen.egg": "Ovo",
  "allergen.fish": "Peixe",
  "allergen.shellfish": "Frutos do mar",
  "allergen.soy": "Soja",
  "allergen.add": "Adicionar a alergia {name}",
  "allergen.rm": "Remover a alergia {name}",

  "diet.omnivore": "Onívora",
  "diet.vegetarian": "Vegetariana",
  "diet.vegan": "Vegana",
  "diet.glutenfree": "Sem glúten",

  "unit.piece": "unidade",

  "expiry.today": "consuma hoje",
  "expiry.tomorrow": "amanhã",
  "expiry.inDays": "em {n} dias",
  "expiry.yesterday": "venceu ontem",
  "expiry.sinceDays": "venceu há {n} dias",

  "search.title": "O que eu cozinho hoje?",
  "search.placeholder": "ex. italiano hoje à noite, menos de 20 min…",
  "search.go": "Buscar",
  "search.run": "Fazer a busca",
  "search.searching": "Procurando receitas…",
  "search.emptyTitle": "Me diga o que você quer",
  "search.emptyBody": "Sugiro receitas com o que você já tem.",
  "search.noResult": "Nenhuma receita encontrada",
  "search.rephrase": "Tente dizer de outro jeito.",
  "search.writing": "Escrevendo a receita…",
  "search.ingredients": "Ingredientes",
  "search.ingredientsShort": "ingredientes",
  "search.steps": "Modo de preparo",
  "search.minutes": "min",
  "search.servings": "porções",
  "search.keep": "Salvar esta receita",
  "search.kept": "Salva",
  "search.savedHead": "Suas receitas salvas",
  "search.forget": "Não salvar mais",
  "search.errSearch": "A busca falhou",
  "search.errDetail": "Não foi possível carregar a receita",
  "search.errKeep": "Não foi possível salvar esta receita",
  "search.errForget": "Não foi possível remover",
  "search.forgetLabel": "Parar de salvar {title}",
  "search.keptLabel": "{title} está salva",
  "inventory.removeLabel": "Remover {name} da geladeira",
  "shopping.storeLabelOne": "Guardar 1 item na geladeira",
  "shopping.storeLabelMany": "Guardar {n} itens na geladeira",
  "cooked.keepLabel": "Manter {name}",
  "cooked.removeLabel": "Remover {name}",
  "feedback.rateLabel": "Dar nota {n} de 5",
  "premium.gateLabel": "Ver a assinatura Premium",
  "premium.gateCta": "Conhecer o Premium — {price} €/mês",
  "search.keepLabel": "Salvar {title}",
  "search.chip1": "Rápido hoje à noite",
  "search.chip2": "Menos de 20 min",
  "search.chip3": "Vegetariano",
  "search.chip4": "Com a minha geladeira",

  "plan.title": "Minha semana",
  "plan.generating": "Montando seu cardápio…",
  "plan.wait": "Uns trinta segundos.",
  "plan.emptyTitle": "Sete dias, zero perguntas",
  "plan.emptyBody":
    "Monto sua semana a partir da sua geladeira, do seu orçamento e da sua dieta.",
  "plan.generate": "Montar minha semana",
  "plan.regenerate": "Refazer a semana",
  "plan.budget": "Orçamento da semana (opcional)",
  "plan.budgetLabel": "Orçamento semanal em euros",
  "plan.cost": "Custo estimado: {cost} €",
  "plan.costBudget": "Custo estimado: {cost} € / orçamento {budget} €",
  "plan.breakfast": "Café da manhã",
  "plan.lunch": "Almoço",
  "plan.dinner": "Jantar",
  "plan.snack": "Lanche",
  "plan.noSteps": "Modo de preparo indisponível.",
  "plan.errGenerate": "Não foi possível montar o cardápio",
  "plan.errSteps": "Não foi possível carregar o preparo",

  "shopping.title": "Minhas compras",
  "shopping.building": "Montando sua lista…",
  "shopping.emptyTitle": "Nunca mais compre repetido",
  "shopping.emptyBody":
    "Parto do seu cardápio e tiro o que você já tem.",
  "shopping.generate": "Montar a lista",
  "shopping.regenerate": "Refazer a lista",
  "shopping.estimate": "Estimativa",
  "shopping.checked": "Marcados",
  "shopping.inFridge": "Já na sua geladeira (vale conferir)",
  "shopping.readd": "+ adicionar",
  "shopping.store": "Já fiz as compras ({n})",
  "shopping.storing": "Guardando…",
  "shopping.stored": "{n} item adicionado à sua geladeira",
  "shopping.storedPlural": "{n} itens adicionados à sua geladeira",
  "shopping.needPlan": "Monte antes um cardápio da semana.",
  "shopping.errGenerate": "Não foi possível montar a lista",
  "shopping.errCheck": "Não foi possível salvar a marcação.",
  "shopping.errStore": "Não foi possível guardar as compras",
  "shopping.toSort": "Para organizar",
  "shopping.check": "Marcar {name}",
  "shopping.uncheck": "Desmarcar {name}",

  "aisle.produce": "Hortifrúti",
  "aisle.dairy": "Laticínios",
  "aisle.meat": "Carnes e peixes",
  "aisle.grocery": "Mercearia",
  "aisle.frozen": "Congelados",
  "aisle.bakery": "Padaria",
  "aisle.other": "Outros",

  "cooked.button": "Eu cozinhei isso",
  "cooked.label": "Marcar esta receita como feita",
  "cooked.question": "O que você terminou?",
  "cooked.remove": "Tirar da minha geladeira",
  "cooked.done": "Geladeira atualizada",
  "cooked.nothing": "Nada para tirar",
  "cooked.readError": "Não foi possível ler sua geladeira",

  "profile.title": "Perfil",
  "profile.budget": "Orçamento semanal",
  "profile.timePerMeal": "Tempo por refeição",
  "profile.diet": "Dieta",
  "profile.goals": "Objetivos",
  "profile.allergies": "Alergias",
  "profile.noAllergy": "nenhuma",
  "profile.signOut": "Sair",
  "profile.signOutLabel": "Sair do aplicativo",
  "profile.errSignOut": "Não foi possível sair",
  "profile.language": "Idioma",

  "premium.active": "Premium ativo — obrigado!",
  "premium.upgrade": "Assinar o Premium",
  "premium.yourTrial": "Seu teste",
  "premium.perMonth": "/mês",
  "premium.daysLeft": "Acesso completo por mais {n} dias",
  "premium.lastDay": "Último dia de acesso completo",
  "premium.remaining": "O que resta este mês.",
  "premium.scans": "escaneamentos",
  "premium.searches": "buscas",
  "premium.willLose": "O que você perde quando o teste acabar",
  "premium.withPremium": "Com o Premium",
  "premium.perk1": "O cardápio da semana, 8 por mês",
  "premium.perk2": "A lista de compras, por seção do mercado",
  "premium.perk3": "100 escaneamentos e 300 buscas por mês",
  "premium.subscribe": "Assinar",
  "premium.keepAccess": "Manter o acesso completo",
  "premium.soon": "O pagamento chega em breve.",
  "premium.errCheckout": "Não foi possível abrir o pagamento",
  "premium.discover": "Ver o Premium",
  "premium.planLocked":
    "O cardápio da semana monta seus sete dias a partir da sua geladeira, do seu orçamento e da sua dieta. Faz parte do Premium.",
  "premium.shoppingLocked":
    "A lista é montada a partir do seu cardápio, organizada por seção e sem o que você já tem. Faz parte do Premium, como o cardápio.",

  "feedback.open": "Deixar minha opinião",
  "feedback.openAgain": "Deixar outra opinião",
  "feedback.label": "Deixar minha opinião sobre o app",
  "feedback.title": "Sua opinião",
  "feedback.hint": "Seja franco, ajuda mais do que ser gentil.",
  "feedback.liked": "Do que você gostou?",
  "feedback.missing": "O que faltou ou te irritou?",
  "feedback.rate": "Dar nota {n} de 5",
  "feedback.needRating": "Escolha uma nota",
  "feedback.thanks": "Obrigado — anotado.",
  "feedback.errSend": "Não foi possível enviar",

  "error.title": "Algo deu errado",
  "error.session": "Sessão expirada — entre de novo.",
  "error.unreachable": "Não foi possível contatar o servidor. Tente daqui a pouco.",
  "error.server": "O servidor respondeu {code}.",
};
